RootWidget:
<RootWidget@BoxLayout>:
    TabbedPanel:
        tab_pos: 'bottom_right'
        do_default_tab: False
        TabbedPanelItem:
            text: 'Tab A'
            Label:
                text: 'This is Tab A.'
        TabbedPanelItem:
            text: 'Tab B'
            Label:
                text: 'This is Tab B.'
        TabbedPanelItem:
            text: 'Tab C'
            Label:
                text: 'This is Tab C.'
            Button:
                text: 'Press me.'
